### ISSUE TITLE
Rest API responding 404 but Proxy working correctly

### ISSUE THREAD

**Issue by wherebrain** [browserup/mitmproxy#12]
Hi,
I would love to use your fork for the extended HAR capabilities. But I have problems with the REST API. I'm on a Ubuntu22 VM.

Traffic is being routed trough the proxy but calling the API is giving 404 errors

Using your node example I get this error when executing the mocha script:

![mocha](https://github.com/browserup/mitmproxy/assets/124807828/bf45456f-0f08-45a8-b5d1-c5910418a891)

screenshot of mitmdump when trying to access the API
![mitmdump](https://github.com/browserup/mitmproxy/assets/124807828/2cf66699-f559-48a0-b905-262482e46031)

REST API server seems to be online
![server](https://github.com/browserup/mitmproxy/assets/124807828/2bd2e268-369a-46b0-ba56-92e1c8617fc0)

Anything I am missing?
Thanks in advance

Mitmproxy: 10.0.0.dev (+1, commit ba23f2c)
Python:    3.10.6
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Linux-5.19.0-46-generic-x86_64-with-glibc2.35

**Comment by JonathanWylie** [comment]
I had a look at the client code you are using.
It is expecting the proxy to be running on: `basePath = 'http://localhost:48088'`
From your screenshot it looks to me like you are listening on port 48080 so the last digit is wrong. Perhaps you have something else running on port 48088 based on the output of netstat?

**Comment by ericbeland** [comment]
I haven't had a chance to take a look yet. 

Just getting my bearings--are you just running the tests that ship with the API clients to see this?

**Comment by wherebrain** [comment]
In the first screenshot I was running the test from [mitmproxy/clients/examples/javascript/test/](https://github.com/browserup/mitmproxy/tree/main/clients/examples/javascript/test)

Also tried [this](https://github.com/browserup/mitmproxy/tree/main/clients/javascript#getting-started) code from the installation instructions with the same error:
![image](https://github.com/browserup/mitmproxy/assets/124807828/3a4e1514-f4e6-42eb-8ba9-f1e18b5b94ee)

**Comment by ericbeland** [comment]
Ah, I think I might see the problem!  Our executable is browserup-proxy, not mitmdump. Our fork adds an extra executable, rather than alter the standard ones.

The other executables don't run our addons, and our addons add the extra routes, so the additional routes won't be there, hence the 404's.

**Comment by ericbeland** [comment]
Can you give it a try with browserup-proxy and let me know how it goes?

**Comment by wherebrain** [comment]
Works flawlessly using your executable. Didn't know about that. Thank you!
